FROM ubuntu:22.04

COPY deploy/cpu-arch.sh .
RUN chmod +x cpu-arch.sh && ./cpu-arch.sh
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && apt install -fy python3 software-properties-common libonig-dev
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy libpq-dev \       
    gcc curl make autoconf libc-dev pkg-config wget libssh2-1-dev libssl-dev bash sshpass zlib1g-dev nginx openssh-server \  
    micro unzip libjpeg-dev libxml2-dev libfreetype6-dev supervisor tini libcurl4-openssl-dev python3-launchpadlib 


RUN add-apt-repository ppa:ondrej/php && \
    apt-get update && \
    export DEBIAN_FRONTEND=noninteractive \
    && apt install -fy php8.3 php8.3-fpm php8.3-curl php8.3-cli php8.3-gd php8.3-exif php8.3-curl php8.3-bcmath  \       
    php8.3-amqp php8.3-uuid php8.3-sockets php8.3-mcrypt php8.3-fileinfo php8.3-mbstring php8.3-intl php8.3-zip \           
    php8.3-swoole php8.3-mongodb php8.3-grpc php8.3-dev php8.3-dom php8.3-opcache composer npm inotify-tools
ENV NODE_VERSION=19.9.0
ENV NVM_DIR /tmp/nvm
WORKDIR $NVM_DIR

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
     
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-enable /usr/local/bin/docker-php-ext-enable
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-install /usr/local/bin/docker-php-ext-install
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-source /usr/local/bin/docker-php-source
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-configure /usr/local/bin/docker-php-ext-configure
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-entrypoint /usr/local/bin/docker-php-entrypoint
COPY --from=php:8.3-fpm /usr/src/php.tar.xz /usr/src/php.tar.xz
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions mysqli  #>> /dev/null 2>&1 || true
RUN install-php-extensions pdo
RUN install-php-extensions pdo-mysql
RUN install-php-extensions pdo-pgsql
RUN install-php-extensions curl
# RUN export PHP_INI_DIR=/etc/php/8.2/cli/ && install-php-extensions openswoole


