FROM ubuntu:22.04

COPY deploy/cpu-arch.sh .
RUN chmod +x cpu-arch.sh && ./cpu-arch.sh
RUN apt update
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy python3         
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  software-properties-common 
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libonig-dev     
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libpq-dev       
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  gcc      
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  curl
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  make            
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  autoconf        
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libc-dev        
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  pkg-config      
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  wget            
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libssh2-1-dev   
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libssl-dev      
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  bash           
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  sshpass         
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  zlib1g-dev      
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  nginx           
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  openssh-server  
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  micro           
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  unzip          
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libjpeg-dev     
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libxml2-dev     
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libfreetype6-dev
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  supervisor      
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  tini            
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  libcurl4-openssl-dev            
RUN export DEBIAN_FRONTEND=noninteractive && apt install -fy  python3-launchpadlib 


RUN add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt install -fy php8.3 php8.3-fpm   
RUN apt install -fy    php8.3-curl            
RUN apt install -fy    php8.3-cli            
RUN apt install -fy    php8.3-gd            
RUN apt install -fy    php8.3-exif          
RUN apt install -fy    php8.3-curl                       
RUN apt install -fy    php8.3-bcmath        
RUN apt install -fy    php8.3-amqp        
RUN apt install -fy    php8.3-uuid        
RUN apt install -fy    php8.3-sockets       
RUN apt install -fy    php8.3-mcrypt       
RUN apt install -fy    php8.3-fileinfo             
RUN apt install -fy    php8.3-mbstring          
RUN apt install -fy    php8.3-intl           
RUN apt install -fy    php8.3-zip           
RUN apt install -fy    php8.3-swoole         
RUN apt install -fy    php8.3-mongodb         
RUN apt install -fy    php8.3-grpc        
RUN apt install -fy    php8.3-dev        
RUN apt install -fy    php8.3-dom        
RUN apt install -fy    php8.3-opcache        
RUN apt install -fy    composer        
RUN apt install -fy    npm
RUN apt install -fy    inotify-tools
ENV NODE_VERSION=19.9.0
ENV NVM_DIR /tmp/nvm
WORKDIR $NVM_DIR

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
     
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-enable /usr/local/bin/docker-php-ext-enable
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-install /usr/local/bin/docker-php-ext-install
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-source /usr/local/bin/docker-php-source
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-ext-configure /usr/local/bin/docker-php-ext-configure
COPY --from=php:8.3-fpm /usr/local/bin/docker-php-entrypoint /usr/local/bin/docker-php-entrypoint
COPY --from=php:8.3-fpm /usr/src/php.tar.xz /usr/src/php.tar.xz
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions mysqli  #>> /dev/null 2>&1 || true
RUN install-php-extensions pdo
RUN install-php-extensions pdo-mysql
RUN install-php-extensions pdo-pgsql
RUN install-php-extensions curl
# RUN export PHP_INI_DIR=/etc/php/8.2/cli/ && install-php-extensions openswoole


