version: v3
teleport:
  nodename: ${TELEPORT_SERVER_NAME}
  data_dir: /var/lib/teleport
  join_params:
    token_name: ${TELEPORT_TOKEN}
    method: token
  proxy_server: ${TELEPORT_DOMAIN}:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ${TELEPORT_PIN}
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    group: docker
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "no"