name: Dockerize
on:
  push:
    branches: [ main ]
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      -
        name: Build and push PHP 8.2
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uscf/php-docker:latest,uscf/php-docker:8.2
          no-cache: true
          file: Dockerfile.8.2
          #test comment
          
      -
        name: Build and push PHP 8.3
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uscf/php-docker:8.3
          no-cache: true
          file: Dockerfile.8.3
          #test comment
