name: Dockerize
on:
  push:
    branches: [ main ]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-buildx:
    strategy:
      matrix:
        php_version: [8.2, 8.3, 5.6, 5.4]
        platform: [linux/amd64, linux/arm64]

    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      -
        name: Build and push PHP images
        run: |
          for php_version in ${matrix.php_version[@]}; do
            export TAG=$(echo "uscf/php-docker:${php_version}")
            docker buildx build --platform $(join-path -- "${{ matrix.platform }}") -f Dockerfile.${php_version} -t $TAG .
            docker tag $TAG uscf/php-docker:$php_version
            if [ "$CI" = "true" ]; then
              docker push $TAG
            fi
          done
